:toc:
:toc-placement!:

:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:caution-caption: :fire:

= URL Dualism Experiment
Ron Kurr <rkurr@jvmguy.com>


toc::[]

== Overview
In the book https://pragprog.com/book/mnee2/release-it-second-edition[Release It! Second Edition: Design and Deploy Production-Ready Software] the author, Michael Nygard, introduces the concept of URL Dualism.  This project attempts to implement the concept in a variety environments, discussing trade-offs and challenges along the way.

== Context
There a few concepts and assumptions that need to be described before we can begin to analyze possible implementations of the URL Dualism pattern.

=== Services Control Their Own Identifiers
The assumption here is that we are working in a world of cooperating services that maintain their own state -- no shared databases.  If you need information, you go the service to get it.  When a new entity is introduced into the system, the service issues the identifier for it.

=== Explicit Context
In the book, Nygard suggest the traditional identifiers are limiting to use because they do not carry enough context to allow a client to locate the authoritative system.  Using a URL provides more context, giving the caller the ability to "tug" on the URL and get more information.

.Identifier Comparison
[source,json]
----
{
    "typical-identifier": "9a9709e6-c3d7-48bf-b394-b3134b907872",
    "explicit-context-identifier": "https://example.com/policies/9a9709e6-c3d7-48bf-b394-b3134b907872"
}
----

=== URL Dualism
URL Dualism is a variation of Explicit Context that emphasizes the fact that a URL can treated two ways. First, it can be treated as an opaque identifier -- just a collection of characters.  It can also be dereferenced and exchanged for more information.  In a REST service, dereferencing an identifier might get you this representation.

.GET https://example.com/policies/9a9709e6-c3d7-48bf-b394-b3134b907872
[source,json]
----
{
    "id": "https://example.com/policies/9a9709e6-c3d7-48bf-b394-b3134b907872",
    "type": "automobile",
    "holder-id": "https://example.com/users/1ccba180-d09f-4236-89db-d1987cbd55af",
    "_links": {
        "self": "https://example.com/policies/9a9709e6-c3d7-48bf-b394-b3134b907872",
        "legacy-system-conversion": "https://example.com/legacy/transformations/9a9709e6-c3d7-48bf-b394-b3134b907872"
    }
}
----

A message based service would use slightly different URLs but the idea remains the same.

.amqp://rabbitmq.example.com/production/policies/9a9709e6-c3d7-48bf-b394-b3134b907872
[source,json]
----
{
    "id": "amqp://rabbitmq.example.com/production/policies/9a9709e6-c3d7-48bf-b394-b3134b907872",
    "type": "automobile",
    "holder-id": "amqp://rabbitmq.example.com/production/users/1ccba180-d09f-4236-89db-d1987cbd55af",
    "_links": {
        "self": "amqp://rabbitmq.example.com/production/policies/9a9709e6-c3d7-48bf-b394-b3134b907872",
        "legacy-system-conversion": "amqp://rabbitmq.example.com/production/legacy/transformations/9a9709e6-c3d7-48bf-b394-b3134b907872"
    }
}
----

== Benefits and Trade-Offs
=== Benefits
One obvious benefit is that service discovery is eliminated.  The identifier contains enough context to point the client to the correct service.  Simply pull on the URL and you will get back enough information to initiate a deeper exchange.

Another benefit manifests when combining formerly disparate systems or combining databases.  In a traditional system, you would likely have id collisions when combining data.  You can almost be guaranteed that both systems will have an entity with the id of `00001`.

Integrating with external systems can be more easily managed using URLs.  Picture an internal identifier that points to a gateway that knows how to convert the internal identifier into calls to an external system.  The gateway can handle transformations and caching.

=== Trade-Offs
It would seem that dereferencing the identifier would be an expensive proposition adding unwanted latency to the service call chain, but Nygard reminds us that caching technology works very well.  If the data returned from the initial dereference contains mostly infrequently changing links to relevant services and operations, caches work great.  The application can cache a handful of recently accessed ids and fetch new ones from Redis.

Security could be an issue when using URLs as identifiers.  Imagine a database gets compromised and the URLs are rewritten to point to an attacker's proxy, allowing him to perform all sort of mischief.

== The Challenges
URL Dualism appears to have more benefits than drawbacks but there is one challenge that still remains: how to keep the URLs stable and still migrate the data between systems and environments?  For example, if I'm developing on my laptop and want to debug using some data from a production system, how do I do that?  The identifiers are going to point production locations and not my local ones.  How do I share test databases between developers and testers?  Is it possible to combine data from two systems and not inadvertently introduce logical duplicates -- different identifiers but they point to effectively the same entity.


== License and Credits
This project is licensed under the https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License].
